/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bana274;

public class App {
     public static void main(String[] args) {        
        Main.main(args);
    }
}
